added new fields
candidatos-info/descritor pull request #3
Opened 2020-06-02 18:15 UTC by ABuarque

Adicionando novos campos para a struct de candidatura e modificando os testes.

2020-06-02 19:15 UTC, danielfireman requested changes

2020-06-02 19:15 UTC, danielfireman commented on candidatura.go
> +	Descricacao       string    `json:"descricao" csv:"desricao"`                    // Descrição da candidatura, informando o tipo e ano.
Pode dar um exemplo, de descrição, por favor? Só para deixar mais claro.

2020-06-02 19:15 UTC, danielfireman commented on candidatura.go
> +	Data              time.Time `json:"data" csv:"data"`                             // Data que a eleição ocorreu.
Tem certeza que queremos guardar a data da eleição para em cada candidatura? Não seria um gasto desnecessário com tanta repetição?

2020-06-02 19:15 UTC, danielfireman commented on candidatura.go
> +	Turno             int       `json:"turno" csv:"turno"`                           // Turno do pleito (1 ou 2).
As candidaturas são são renovadas a cada turno? O que acontece com candidatos que participaram do primeiro e do segundo turno?

Perguntando pois talvez esse também precise ser um identificador.

2020-06-02 19:15 UTC, danielfireman commented on candidatura.go
> +	Email             string    `json:"email" csv:"email"`                           // Email do candidato.
Sabe dizer se esse campo é obrigatório?

2020-06-02 19:15 UTC, danielfireman commented on candidatura.go
> +	Situacao          string    `json:"situacao" csv:"situacao"`                     // Situação da candidatura (podendo ser APTO ou INAPTO).
`AptidaoCandidatura` ?

Seria bacana também complementar essa documentação com os casos em que temos uma ou outra. Se você puder encontrar. 

Perguntando pois esse será nosso dicionário de dados oficial, digamos assim.

2020-06-02 19:15 UTC, danielfireman commented on candidatura.go
> +	SituacaoCandidato string    `json:"situacao_candidato" csv:"situacao_candidato"` // Situação do candidato (pondendo ser DEFERIDO ou INDEFERIDO).
Seria bacana ter mais documentação aqui também. Principalmente pela similaridade com o campo acima

2020-06-02 19:15 UTC, danielfireman commented on candidatura.go
> +	UFOrigem          string    `json:"uf_origem" csv:"uf_origem"`                   // Identificador (2 caracteres) da unidade federatirva de nascimento do candidato.
`UFCandidato`

Colocar todos os campos sobre o candidato em uma struct separada? Dessa forma não precisamos ficar repetindo que os dados são a respeito do candidato pois eles estarão dentro de um contexto.

Abaixo fiz diversos pedidos para adicionar o sufixo candidato para diminuir a ambiguidade, uma vez que a struct é referente a candidatura

2020-06-02 19:15 UTC, danielfireman commented on candidatura.go
> +	UFOrigem          string    `json:"uf_origem" csv:"uf_origem"`                   // Identificador (2 caracteres) da unidade federatirva de nascimento do candidato.
```suggestion
	UFOrigem          string    `json:"uf_origem" csv:"uf_origem"`                   // Identificador (2 caracteres) da unidade federativa de nascimento do candidato.
```

2020-06-02 19:15 UTC, danielfireman commented on candidatura.go
> +	MunicipioOrigem   string    `json:"municipio_origem" csv:"municipio_origem"`     // Município de nascimento do candidato.
`MunicipioCandidato`

2020-06-02 19:15 UTC, danielfireman commented on candidatura.go
> +	Nascimento        time.Time `json:"nascimento" csv:"nascimento"`                 // Data de nascimento do candidato.
`DataNascCandidato`

2020-06-02 19:15 UTC, danielfireman commented on candidatura.go
> +	TituloEleitoral   string    `json:"titulo_eleitoral" csv:"titulo_eleitoral"`     // Titulo eleitoral do candidato.
`TituloEleitoralCandidato`

2020-06-02 19:15 UTC, danielfireman commented on candidatura.go
> +	Gênero            string    `json:"genero" csv:"genero"`                         // Gênero do candidato (MASCULINO ou FEMININO).
`GeneroCandidato` (não acho que precisamos acentuar nomes de campos)

2020-06-02 19:15 UTC, danielfireman commented on candidatura.go
> +	GrauInstrucao     string    `json:"grau_instrucao" csv:"grau_instrucao"`         // Grau de instrução do candidato.
`GrauInstrucaoCandidato`

2020-06-02 19:15 UTC, danielfireman commented on candidatura.go
> +	EstadoCivil       string    `json:"estado_civil" csv:"estado_civil"`             // Estado civil do candidato.
`EstadoCivilCandidato`

2020-06-02 19:15 UTC, danielfireman commented on candidatura.go
> +	Raca              string    `json:"raca" csv:"raca"`                             // Raca do candidato (como BRANCA ou PARDA).
`RacaCandidato`

2020-06-02 19:19 UTC, ABuarque commented on candidatura.go
> +	Descricacao       string    `json:"descricao" csv:"desricao"`                    // Descrição da candidatura, informando o tipo e ano.
Claro, um seria "Eleições Municipais 2016"

2020-06-02 19:30 UTC, ABuarque commented on candidatura.go
> +	Email             string    `json:"email" csv:"email"`                           // Email do candidato.
Provavelmente sim visto que de certeza todos os candidatos do estado de Sergipe possuem email publicado pelo CSV

2020-06-03 01:11 UTC, ABuarque commented on candidatura.go
> +	Turno             int       `json:"turno" csv:"turno"`                           // Turno do pleito (1 ou 2).
Para cada turno os dados do candidato são todos reinscritos, um exemplo que posso lhe dar da eleição de 2016 foi o caso de Rui Palmeira, comparando as duas linhas no CSV que são destinadas a ele os únicos campos que mudam são o turno, sai de 1 para 2, a situação da eleição, que sai de "segundo turno" para "eleito" e o código de situação de eleição. 

O número do protocolo de candidatura e número de processo se mantem para primeiro e segundo turnos.

2020-06-03 02:14 UTC, ABuarque commented on candidatura.go
> +	Situacao          string    `json:"situacao" csv:"situacao"`                     // Situação da candidatura (podendo ser APTO ou INAPTO).
Concordo que aptidao fica melhor. Só não ficou claro o que você sobre complementar a documentação...coloco como comentários no arquivo mesmo?

2020-06-03 11:55 UTC, danielfireman commented on candidatura.go
> +	Situacao          string    `json:"situacao" csv:"situacao"`                     // Situação da candidatura (podendo ser APTO ou INAPTO).
Isso! Comentários do arquivo está perfeito.

2020-06-03 12:02 UTC, danielfireman commented on candidatura.go
> +	Turno             int       `json:"turno" csv:"turno"`                           // Turno do pleito (1 ou 2).
Excelente explicação! Com isso vejo que temos mudar algumas coisas na forma que armazenamos os dados. Levando em conta que queremos manter um arquivo por candidatura e que temos restrições de armazenamento, uma possível solução é mudar o layout do struct. Onde teremos separados os dados de cada turno. Um exemplo grosseiro:

```go
type Candidatura struct {
  Leg
  Cargo
  CPF
  InfoPessoal
  Turno1
  Turno2
  ... 
}
```

O que nos leva a pensar direitinho o layout das informações no CSV. O que acha?  Pode fazer fazer uma proposta, por favor?

2020-06-03 19:20 UTC, ABuarque commented on candidatura.go
> +	Turno             int       `json:"turno" csv:"turno"`                           // Turno do pleito (1 ou 2).
Eu penso o seguinte: Considerando que na prática só o campo stituacao_eleicao muda de um turno para o outro (ja que o codigo_situacao_eleicao não nos é necessário), acho que por simplicidade podíamos apenas fazer dois campos na raiz da struct: situacao_primeiro_turno e situacao_segundo_turno, e colocar o prefixo como vc falou, o que me diz?

2020-06-03 20:54 UTC, danielfireman commented on candidatura.go
> +	Turno             int       `json:"turno" csv:"turno"`                           // Turno do pleito (1 ou 2).
Me parece ótimo!

2020-06-03 23:36 UTC, danielfireman approved these changes
Muito bacana! Faltou só um

2020-06-03 23:36 UTC, danielfireman commented on candidatura.go
> +	Candidato
Faltaram só o tipo e o struct tags

2020-06-03 23:36 UTC, danielfireman approved these changes
Muito bacana! Só um pequeno detalhe abaixo.

2020-06-04 02:38 UTC, ABuarque commented on candidatura.go
> +	Candidato
Tipo e tags? Não to lembrado desses...

2020-06-04 18:56 UTC, danielfireman approved these changes

2020-06-04 19:12 UTC, merged